name: Tablet Continuous Integration
on: [push]
permissions:
  contents: write
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
          dry_run: true
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"
      - name: Minify and package
        run: ./minify.sh
      - name: Upload minified package
        uses: actions/upload-artifact@v4
        with:
          name: tablet.html.gz
          path: build/tablet.html.gz
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.event.outputs.tag.name }}
          files: |
            build/target.html.gz
            draft: True
